version: 0.0
os: linux

files:
  - source: server
    destination: /var/node/krate-events/server
  - source: client
    destination: /var/node/krate-events/client
hooks:
  BeforeInstall:
    - location: scripts/remove_old_app.sh
      timeout: 300
      runas: bitnami
  AfterInstall:
    - location: scripts/build_angular.sh
      timeout: 300
      runas: bitnami
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: bitnami
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: bitnami
